const data = {
  pro: [
    {
    
      Title: "Chebba Chews CARAMEL",
      Link:"Chebba-Chews-CARAMEL",
      Category: "TAFFY",
      Image: "/images/Cheebba Caramel.png",
      ImageP: "/images/Caramel_THC_PUB.png",
      Price: 15.99,
      CInStock: 15,
      Brand: "Chebba Chews",
      Rate: 4.4,
      NbrView: 20,
      Ingredients:
        "Sugar, Glucose Syrup, Palm Oil, Nonfat Milk, Sorbitol, starch modified (tapioca), Butter Flavor, Salt, Food Carrageenan, Natural Flavors, Soy Lecithin, Mono & Diglycerides, Disodium Phosphate, Sodium CitRate.",
      Description:
        "Full spectrum hemp derived CBD infused caramel. Approximately 25mg cannabidiol per chew. Organically cultivated, USA grown hemp extract. Just 12 calories per serving",
    },
    {

      Title: "STRAWBERRY HEMP TAFFY",
      Link:"STRAWBERRY-HEMP-TAFFY",
      Category: "TAFFY",
      Image: "/images/Cheebba Strawberry.png",
      ImageP: "/images/strawberryIndicaPUB.png",
      Price: 15.99,
      CInStock: 10,
      Brand: "Chebba Chews",
      Rate: 4.0,
      NbrView: 13,
      Ingredients:
        "Glucose Syrup, Sugar, Mono- and Diglycerides, Natural Flavors, Malic Acid, Egg Whites, Citric Acid, Natural and Artificial Colors.",
      Description:
        "Full spectrum hemp derived CBD infused strawberry taffy. Organically cultivated, USA grown hemp extract Approx. 25mg cannabidiol per chew. Just 11 calories per serving",
    },{
    
      Title: "Chebba Chews SLEEPY CHEW",
      Link:"Chebba-Chews-SLEEPY-CHEW",
      Category: "CBN TAFFY",
      Image: "/images/Cheebba Sleppy.png",
      ImageP: "/images/SleppyCBN+THC.png",
      Price: 15.99,
      CInStock: 15,
      Brand: "Chebba Chews",
      Rate: 4.7,
      NbrView: 38,
      Ingredients:
        "Sugar, Glucose Syrup, Palm Oil, Nonfat Milk, Sorbitol, starch modified (tapioca), Butter Flavor, Salt, Food Carrageenan, Natural Flavors, Soy Lecithin, Mono & Diglycerides, Disodium Phosphate, Sodium CitRate.",
      Description:
        "Hemp derived CBD/CBN infused chocolate taffy. Organically cultivated, USA grown hemp extract. Approx. 25mg CBD per chew. Approx. 2.5mg CBN per chew. Nightly Sleep-Aid",
    },
    {
      Title: "Bursts Pulled Taffy",
      Link: "Bursts-Pulled-Taffy",
      Category: "Hybrid",
      Image: "/images/Fruit-Choco.png",
      ImageP: "",
      Price: 16.990,
      CInStock: 8,
      Brand: "Dixie",
      Rate: 4.8,
      NbrView: 25,
      Ingredients: "Gluten free, dairy free and nut free",
      Description:
        "Dixie Bursts are an assorted pack of three fruity flavors that are sure to make any situation shine a little brighter. The mango, blue raspberry and strawberry taffies are bursting with flavor and are the ultimate discreet dosing edible. Individually wrapped, you can take them anywhere your adventure takes you. ",
    },
    {
      Title: "Bursts Pulled Taffy",
      Link: "Bursts-Pulled-Taffy",
      Category: "Indica",
      Image: "/images/Fruit-Choco2.png",
      ImageP: "",
      Price: 16.990,
      CInStock: 18,
      Brand: "Dixie",
      Rate: 4.4,
      NbrView: 21,
      Ingredients: "Gluten free, dairy free and nut free",
      Description:
        "Dixie Bursts are an assorted pack of three fruity flavors that are sure to make any situation shine a little brighter. The mango, blue raspberry and strawberry taffies are bursting with flavor and are the ultimate discreet dosing edible. Individually wrapped, you can take them anywhere your adventure takes you.",
    },
    {
      Title: "Bursts Pulled Taffy",
      Link: "Bursts-Pulled-Taffy",
      Category: "Staiva",
      Image: "/images/Fruit-Choco-3.png",
      ImageP:"",
      Price: 16.900,
      CInStock: 12,
      Brand: "Dixie",
      Rate: 4.4,
      NbrView: 19,
      Ingredients: "Gluten free, dairy free and nut free",
      Description:
        "Dixie Bursts are an assorted pack of three fruity flavors that are sure to make any situation shine a little brighter. The mango, blue raspberry and strawberry taffies are bursting with flavor and are the ultimate discreet dosing edible. Individually wrapped, you can take them anywhere your adventure takes you.",
    },
    {
      Title: "Birthday Cake",
      Link:  "Birthday-Cake-Kiva-Bar",
      Category: "THC",
      Image:  "/images/Birthday Cake Kiva Bar_1.png",
      ImageP:  "/images/Birthday Cake Kiva Bar_2.png",
      Price:  10.900,
      CountIntStock: 15,
      Brand:  "Kiva",
      Rate:  3.8,
      NbrView :  10,
      Ingredient:  "White Chocolate (Sugar, Cocoa Butter, Milk, Sunflower Lecithin, Vanilla), Sprinkles (Sugar, Hydrogenated Palm Kernel Oil, Corn Starch, Sunflower Lecithin, FD&C Colors (Yellow #6 Lake, Yellow #5 Lake, Blue #1 Lake, Red #40 Lake, Red #3 Dye), Maltodextrin, Carnauba Wax, Vanillin, Cellulose Gum), Spirulina Extract for Color, Natural Flavor, Cannabis Extract.",
      Description:  "Now you can eat your cake and feel it too! The Birthday Cake Kiva Bar tastes like gourmet lemon-vanilla cake topped with whipped buttercream frosting and celebratory sprinkles. Infused with cold water hash for a multi-layered experience, this bar is one delish birthday wish come true."
  },
  {
    Title: "Blackberry Blitz",
    Link:  "Blackberry-Blitz",
    Category: "Sativa",
    Image:  "/images/Blackberry Blitz_1.png",
    ImageP:  "/images/Blackberry Blitz_1.png",
    Price:  12.900,
    CountIntStock: 6,
    Brand:  "Kiva",
    Rate:  3.2,
    NbrView :  14,
    Ingredient:  "s",
    Description:  "It’s GAME ON with these Blackberry Blitz Camino gummies. Blackberry Blitz encourages a challenge, whether on or off the field. The exhilarating blend of sativa-like terpenes with fresh blackberry flavors will have you pumped from pre-game through overtime. Let’s Play."
},
{
  Title: "Midnight Blueberry",
  Link:  "Midnight-Blueberry",
  Category: "THC",
  Image:  "/images/Midnight Blueberry_1.png",
  ImageP:  "/images/Midnight Blueberry_2.png",
  Price:  14.900,
  CountIntStock: 12,
  Brand:  "Kiva",
  Rate: 3.1,
  NbrView :  11,
  Ingredient:  "Organic Tapioca Syrup, Sugar, Gelatin, Malic Acid, Natural Flavors, Citric Acid, Cannabis Extract, Fruit and Vegetable Juice for Color, Chamomile Extract, Lavender Exract, Natural Terpenes, Coconut Oil, Carnauba Wax.",
  Description:  "Settle in for a smooth slumber by a serene lake and let all your worries go. Kiva’s Midnight Blueberry Camino gummies offer a calming combination of 5 MG of THC, 1 MG of CBN and relaxing terpenes with chamomile and lavender extracts to promote restful sleep. Take one before bed and enjoy a night of tranquil effects. Sweet dreams!"
},
{
  Title: "Pineapple Habanero",
  Link:  "Pineapple-Habanero",
  Category: "Sativa",
  Image:  "/images/Pineapple Habanero_1.png",
  ImageP:  "/images/Pineapple Habanero_2.png",
  Price:  13.900,
  CountIntStock: 10,
  Brand:  "Kiva",
  Rate:  2.4,
  NbrView :  9,
  Ingredient:  "Sugar, Tapioca Syrup, Water, Pectin, Natural Watermelon Flavor WONF, Sodium Citrate, Citric Acid, Malic Acid, Sodium Hydrogen Malate, Cannabis Extract, Fruit & Vegetable Juice for Color, Coconut Oil, Carnauba Wax, Terpenes.",
  Description:  "Get a taste of the Southwest and invigorate your senses. Kiva’s Pineapple Habanero Camino gummies pair energy-stimulating sativa-like terpenes with ripe pineapple and a touch of heat."
},
{
  Title: "S'mores",
  Link: "S-mores",
  Category: "Staiva",
  Image: "/images/S'mores_1.png",
  ImageP:  "/images/S'mores_2.png",
  Price: 17.900,
  CInStock: 12,
  Brand: "Kiva",
  Rate: 4.3,
  NbrView: 24,
  Ingredients: "Milk Chocolate (Sugar, Cocoa Butter, Milk, Unsweetened Chocolate, Sunflower Lecithin, Vanilla), Marshmallow (Sugar, Corn Syrup, Modified Starch, Gelatin, Sodium Hexametaphosphate, Artificial Flavor, Natural Flavor, Artificial Color (Blue 1)), Graham Cracker (Whole Grain Wheat, Corn Meal, Sugar, Brown Sugar Syrup, Canola And/Or Sunflower Oil, Honey, Baking Soda, Salt, Glucose, Trisodium Phosphate, Natural Flavor), Natural Flavors, Cannabis Extract.",
  Description:
    "Get lit by a different kind of fire with a hot Kiva take on an old classic. The Kiva Smores Bar features sweet milk chocolate stacked with chewy marshmallow pieces and crunchy graham cracker chunks. Each square contains 5MG of THC, the perfect amount to make you one happy camper… and leave you wanting s’more.",
},{
  Title: "Everything Bagel Seasoning Munchies Bar",
  Link: "Everything-Bagel-Seasoning-Munchies-Bar",
  Category: "THC",
  Image: "/images/Everything Bagel Seasoning Munchies Bar_1.png",
  ImageP:  "/images/Everything Bagel Seasoning Munchies Bar_2.png",
  Price: 19.900,
  CInStock: 12,
  Brand: "Kiva",
  Rate: 4.7,
  NbrView: 29,
  Ingredients: "Semisweet Chocolate (Sugar, Unsweetened Chocolate, Cocoa Butter, Potassium Carbonate, Sunflower Lecithin, Vanilla), Everything Bagel Seasoning (Sesame Seeds, Black Sesame Seeds, Poppy Seeds, Garlic, Onion and Salt), Cannabis Extract.",
  Description:
    "This year's Munchies Bar is EVERYTHING. A collab with LA bagel food truck pioneers The Yeastie Boys, Kiva's Everything Bagel Munchies Bar features an exclusive blend of the Yeastie's classic salty seasoning sprinkled on sweet, hash-infused dark chocolate. Sugary, savory, chocolatey and hashy, this limited edition treat is sure to transform your wake and bake, Kiva-style.",
},{
  Title: "Blackberry Dark Chocolate",
  Link: "Blackberry-Dark-Chocolate",
  Category: "THC",
  Image: "/images/Blackberry Dark Chocolate_1.png",
  ImageP:  "/images/Blackberry Dark Chocolate_2.png",
  Price: 16.900,
  CInStock: 14,
  Brand: "Kiva",
  Rate: 4.7,
  NbrView: 29,
  Ingredients: "Semisweet Chocolate (Sugar, Unsweetened Chocolate, Cocoa Butter, Potassium Carbonate, Sunflower Lecithin, Vanilla), Cannabis Extract, Blackberry Flavor WONF.",
  Description:
    "A blend of fresh blackberries and toasty cannabis come together in rich, dark chocolate to create a unique flavor that lingers on your palate. Let the tart berry aroma mingle with the 54% cacao and savor this superb culinary combination. Like all Kiva’s chocolates, our Blackberry Bar is made with sustainably-sourced cacao infused with pure, clean cold water hash for a fuller, richer cannabis experience that honors the essence of the whole plant.",
},{
  Title: "Dark Chocolate",
  Link: "Dark Chocolate",
  Category: "THC",
  Image: "/images/Dark Chocolate_1.png",
  ImageP:  "/images/Dark Chocolate_2.png",
  Price: 16.900,
  CInStock: 15,
  Brand: "Kiva",
  Rate: 4.6,
  NbrView: 26,
  Ingredients: "Semisweet Chocolate (Unsweetened Chocolate, Sugar, Cocoa Butter, Sunflower Lecithin, Vanilla), Cannabis Extract.",
  Description:
    "Our classic Dark Chocolate bar is uniquely complex with flavors of black coffee and dark cherry. Using a 57% sustainably-sourced dark chocolate infused with pure, clean cold water hash, this bar is sure to delight any true chocolate lover.",
},{
  Title: "Espresso Dark Chocolate CBD 1:1",
  Link: "Espresso-Dark-Chocolate-CBD-1-1",
  Category: "THC",
  Image: "/images/Espresso Dark Chocolate CBD 1_1_1.png",
  ImageP:  "/images/Espresso Dark Chocolate CBD 1_1_2.png",
  Price: 16.900,
  CInStock: 13,
  Brand: "Kiva",
  Rate: 4.8,
  NbrView: 25,
  Ingredients: "Semisweet Chocolate (Sugar, Unsweetened Chocolate, Cocoa Butter, Potassium Carbonate, Sunflower Lecithin, Vanilla), Cannabis Extract, Espresso Flavor.",
  Description:
    "Balance is not something you find, it’s something you create. With Kiva's 1:1 CBD Dark Chocolate Espresso Bar we’ve created the ideal 1:1 balance of CBD to THC. Infused with cold water hash and delicious notes of freshly brewed espresso, this bar is a harmonious combination of flavors and effects that will make the world slow down - even if just for a moment.",
},{
  Title: "Dark Chocolate CBD 5:1",
  Link: "Dark-Chocolate-CBD-5-1",
  Category: "THC",
  Image: "/images/Dark Chocolate CBD 5_1_1.png",
  ImageP:  "/images/Dark Chocolate CBD 5_1_2.png",
  Price: 16.900,
  CInStock: 12,
  Brand: "Kiva",
  Rate: 4.7,
  NbrView: 29,
  Ingredients: "Semisweet Chocolate (Unsweetened Chocolate, Sugar, Cocoa Butter, Sunflower Lecithin, Vanilla), Cannabis Extract.",
  Description:
    "Deep breaths and small bites. That’s the mantra behind our 5:1 CBD-dominant Dark Chocolate Kiva Bar that combines our robust, cold water hash-infused dark chocolate with hints of vanilla, and a silky smooth texture. With 5MG of CBD and 1MG of THC per serving, it gives you the ability to indulge without overdoing it. So have a bite or two, relax and let your energy be restored.",
},
{
  Title: "Sparkling Pear",
  Link: "Sparkling-Pear",
  Category: "MINTS",
  Image: "/images/Sparkling Pear_1.png",
  ImageP:"/images/Sparkling Pear_2.png",
  Price: 17.900,
  CInStock: 0,
  Brand: "Kiva",
  Rate: 4.2,
  NbrView: 25,
  Ingredients:
    "Organic Tapioca Syrup, Sugar, Gelatin, Natural Flavors, Malic Acid, Citric Acid, Cannabis Extract, Natural Terpenes, Coconut Oil, Carnauba Wax.",
  Description:
    "Kick back and transport yourself to wine country with Kiva’s Sparkling Pear Camino gummies. The unconventional ratio of CBD to THC creates a euphoric experience without any anxiety.",
},
{
  Title: "Wild Berry",
  Link: "Wild-Berry",
  Category: "THC",
  Image: "/images/Wild Berry_1.png",
  ImageP:  "/images/Wild Berry_2.png",
  Price: 16.900,
  CInStock: 12,
  Brand: "Kiva",
  Rate: 4.7,
  NbrView: 32,
  Ingredients: "Sugar, Tapioca Syrup, Water, Pectin, Natural Lemon Lime Flavor WONF, Sodium Citrate, Citric Acid, Malic Acid, Sodium Hydrogen Malate, Spirulina Extract for Color, Fruit & Vegetable Juice for Color, Cannabis Extract, Coconut Oil, Carnauba Wax, Terpenes.",
  Description:
    "Go on a relaxing coastal stroll with Kiva’s Wild Berry Camino gummies. The calming, indica-like terpenes pair with notes of wild blackberry and fresh raspberry for a laid-back weekend vibe.",
},
{
  Title: "Passionfruit Punch",
  Link: "Passionfruit-Punch",
  Category: "THC",
  Image: "/images/Passionfruit Punch_1.png",
  ImageP:  "/images/Passionfruit Punch_1.png",
  Price: 16.900,
  CInStock: 12,
  Brand: "Kiva",
  Rate: 4.9,
  NbrView: 58,
  Ingredients: "Tapioca Syrup, Sugar, Gelatin, Malic Acid, Natural Flavors, Cannabis Extract, Citric Acid, Potassium Sorbate, Coconut Oil, Carnauba Wax, Mica-based Pearlescent Pigment, Corn Starch, Fruit and Vegetable Juice for Color, Terpenes.",
  Description:
    "The much-anticipated product features a new Passionfruit Punch flavor, and a reimagined landscape featuring San Francisco’s historic Pink Triangle. Once a symbol of hate and intolerance, the Pink Triangle brings attention to the past persecution of the gay community and reminds us to ensure it never happens again.",
}
  ],
};

export default data;
